# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:com/izpan/modules/*/repository/mapper/*Mapper.xml
  typeAliasesPackage: com.izpan.modules.**.domain.entity
  global-config:
    banner: false
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      table-underline: true
      logic-delete-field: is_deleted